name: Pkg - Release and Publish
on:
  workflow_call:
    inputs:
      enable-test-unit:
        default: true
        description: Enable unit tests => pnpm run test:unit
        type: boolean
    secrets:
      NPM_TOKEN:
        required: true
      GH_TOKEN:
        description: provided by secrets.GITHUB_TOKEN
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  HUSKY: 0

jobs:
  setup:
    name: Setup workflow
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ steps.get-node-npm-version.outputs.NODE_VERSION }}
      PNPM_VERSION: ${{ steps.get-node-npm-version.outputs.PNPM_VERSION }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Node and PNPM version
        id: get-node-npm-version
        run: |
          echo "NODE_VERSION=$(cat package.json | jq -r '.volta.node')" >> $GITHUB_OUTPUT
          echo "PNPM_VERSION=$(cat package.json | jq -r '.packageManager' | awk -F'@' '{print $2}')" >> $GITHUB_OUTPUT

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ needs.setup.outputs.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i --prefer-offline

      - name: Check unit tests
        if: ${{ inputs.enable-test-unit }}
        run: pnpm run test:unit

      - name: Build
        run: pnpm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release
