name: Get basic information
on:
  workflow_call:
    outputs:
      NODE_VERSION:
        description: Node.js version
        value: ${{ jobs.setup.outputs.NODE_VERSION }}
      PNPM_VERSION:
        description: PNPM version
        value: ${{ jobs.setup.outputs.PNPM_VERSION }}

env:
  HUSKY: 0

jobs:
  setup:
    name: Setup workflow
    runs-on: ubuntu-latest
    outputs:
      NODE_VERSION: ${{ steps.get-node-npm-version.outputs.NODE_VERSION }}
      PNPM_VERSION: ${{ steps.get-node-npm-version.outputs.PNPM_VERSION }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Node and PNPM version
        id: get-node-npm-version
        run: |
          echo "NODE_VERSION=$(cat package.json | jq -r '.volta.node')" >> $GITHUB_OUTPUT
          echo "PNPM_VERSION=$(cat package.json | jq -r '.packageManager' | awk -F'@' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Log outputs
        run: |
          echo "NODE_VERSION: ${{ steps.get-node-npm-version.outputs.NODE_VERSION }}"
          echo "PNPM_VERSION: ${{ steps.get-node-npm-version.outputs.PNPM_VERSION }}"
